# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mostra_calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='porcentagem_acerto',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
